repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
      - id: end-of-file-fixer
        name: end-of-file-fixer
      - id: check-added-large-files
        name: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        types_or:
          - toml
          - json
          - markdown
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
  - repo: https://github.com/python-jsonschema/check-jsonschema/
    rev: 0.15.1
    hooks:
      - id: check-metaschema
        name: check-metaschema
        types:
          - json
      - id: check-jsonschema
        name: .github/workflows/pre-commit.yml schema
        files: ^\.github/workflows/pre-commit\.yml$
        args:
          - --schemafile
          - python/.github/workflows/pre-commit.json
