[nitpick.styles]
include = [
  "../base",
  "../editorconfig",
  "gitattributes",
  "pre-commit",
  "pyproject/pyproject",
  "gh-actions",
  "bumpversion",
  "flake8",
  "isort",
  "yamllint",
  # Files that shouldn't exist in Python projects
  "py://nitpick/resources/python/absent",
  # All Python projects must use autoflake via pre-commit
  "py://nitpick/resources/python/autoflake"
]

# Use prettier to format TOML and CSS files
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/pre-commit/mirrors-prettier"

[[".pre-commit-config.yaml".repos.hooks]]
id = "prettier"
types_or = ["toml", "css"]
additional_dependencies = [
  "prettier",
  "prettier-plugin-toml",
]
