[nitpick.styles]
include = [
  "../base",
  "../editorconfig",
  "gitattributes",
  "pre-commit",
  "pyproject/pyproject",
  "gh-actions",
  "bumpversion",
  "flake8",
  "isort",
  "yamllint",
  # Files that shouldn't exist in Python projects
  "py://nitpick/resources/python/absent",
  # All Python projects must use autoflake via pre-commit
  "py://nitpick/resources/python/autoflake"
]

[nitpick.files.present]
"setup.cfg" = "You must create a setup.cfg to store the flake8 configuration."

[nitpick.files.absent]
".flake8" = """Create a setup.cfg and store the flake8 configuration inside a
[flake8] section for better support of INI files syntax highlighting by editors."""

# https://nitpick.readthedocs.io/en/latest/nitpick_section.html#comma-separated-values
[nitpick.files."setup.cfg"]
comma_separated_values = ["flake8.ignore", "flake8.exclude"]
