# All Python projects use Github Actions to run CI

# --- Schema validation for .github/workflows/pre-commit.yml ---

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/python-jsonschema/check-jsonschema"

[[".pre-commit-config.yaml".repos.hooks]]
id = "check-jsonschema"
name = "jsonschema: .github/workflows/pre-commit.yml"
files = "^\\.github/workflows/pre-commit\\.yml$"
args = [
    "--schemafile",
    "https://raw.githubusercontent.com/mondeja/nitpick-styles/master/python/.github/workflows/pre-commit.json"
]

# --- ---
