# All Python projects use Github Actions to run CI
[nitpick.files.present]
".github/workflows/pre-commit.yml" = "You must create the file .github/workflows/pre-commit.yml"
".github/workflows/pre-commit-autoupdate.yml" = "You must create the file .github/workflows/pre-commit-autoupdate.yml"
".github/workflows/update-copyright-years.yml" = "You must create the file .github/workflows/update-copyright-years.yml"

[nitpick.files.absent]
".github/workflows/update-copyright-years-in-license-file.yml" = "Rename to .github/workflows/update-copyright-years.yml"
