# All Python projects must run isort via pre-commit
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/PyCQA/isort"

[[".pre-commit-config.yaml".repos.hooks]]
id = "isort"

# Common configuration for all Python projects
["pyproject.toml".tool.isort]
lines_after_imports = 2
multi_line_output = 3
use_parentheses = true
combine_as_imports = true
include_trailing_comma = true
known_tests = "tests"
sections = ["STDLIB", "THIRDPARTY", "FIRSTPARTY", "TESTS", "LOCALFOLDER"]
