# All Python projects must use pre-commit
[nitpick.files.present]
".pre-commit-config.yaml" = "You must create a .pre-commit-config.yaml file at the root of the project."

# All Python projects must use pyupgrade
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/asottile/pyupgrade"

[[".pre-commit-config.yaml".repos.hooks]]
id = "pyupgrade"

# All Python projects must use trailing commas in multiline expressions
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/asottile/add-trailing-comma"

[[".pre-commit-config.yaml".repos.hooks]]
id = "add-trailing-comma"
name = "add-trailing-comma"


[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"

# Remove trailing whitespaces from files in Python projects
# using pre-commit directly
[[".pre-commit-config.yaml".repos.hooks]]
id = "trailing-whitespace"
# I like that hook identifiers show their ids when running,
# not their readable names, I feel that really ugly
name = "trailing-whitespace"

# Fix end of files in Python projects using pre-commit
[[".pre-commit-config.yaml".repos.hooks]]
id = "end-of-file-fixer"
name = "end-of-file-fixer"

# All Python projects must use the debug-statements hook:
# https://github.com/pre-commit/pre-commit-hooks#debug-statements
[[".pre-commit-config.yaml".repos.hooks]]
id = "debug-statements"
name = "debug-statements"


# All Python projects must have their setup.cfg correctly formatted
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/asottile/setup-cfg-fmt"

[[".pre-commit-config.yaml".repos.hooks]]
id = "setup-cfg-fmt"


# All Python projects must expose their development dependencies
# in a [dev] group and keep synced their development dependencies
# with other groups of dependencies
# https://github.com/mondeja/pre-commit-hooks#dev-extras-required
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/mondeja/pre-commit-hooks"

[[".pre-commit-config.yaml".repos.hooks]]
id = "dev-extras-required"


# All Python projects must use Nitpick itself via pre-commit
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/andreoliwa/nitpick"

[[".pre-commit-config.yaml".repos.hooks]]
id = "nitpick-check"
name = "nitpick"


# All Python projects must include LICENSE and README.md in MANIFEST.in file
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/mondeja/pre-commit-hooks"

[[".pre-commit-config.yaml".repos.hooks]]
id = "file-check-lines"
name = "MANIFEST.in includes"
files = "^MANIFEST\\.in$"
args = [
  "include README.md",
  "include LICENSE"
]


# --- .editorconfig with pre-commit ---

# In Python projects we check that editorconfig rules are followed
# by using pre-commit
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/editorconfig-checker/editorconfig-checker.python"

[[".pre-commit-config.yaml".repos.hooks]]
id = "editorconfig-checker"
name = "editorconfig-checker"

# --- ---
