[nitpick.styles]
include = ["../base"]

# The pyupgrade pre-commit hook must use the correct argument
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/asottile/pyupgrade"

[[".pre-commit-config.yaml".repos.hooks]]
id = "pyupgrade"
args = ["--py37-plus"]

# The add-trailing-comma pre-commit hook must use the correct argument
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/asottile/add-trailing-comma"

[[".pre-commit-config.yaml".repos.hooks]]
id = "add-trailing-comma"
args = ["--py37-plus"]

# Define a strict minimum version required to install in setup.cfg
["pyproject.toml".tool.poetry.dependencies]
python = "^3.7"

# Configure the Python version that isort targets.
#
# This is useful for giving to isort the exact libraries
# that must group as standard ones. We configure here all
# standard libraries added in subsecuents versions.
#
# Without this, if we import, for example, a standard library
# removed in 3.6 or previous version that would be grouped
# inside the standard libraries, which would lead to confusion
# and possibly unexpected behaviour at runtime
["pyproject.toml".tool.isort]
py_version = 37
extra_standard_library = [
    # https://docs.python.org/3/whatsnew/3.8.html#new-modules
    "importlib.metadata",

    # https://docs.python.org/3/whatsnew/3.9.html#new-modules
    "zoneinfo",
    "graphlib",

    # 3.10 does not add new modules

    # 3.11 is not stable
    # https://docs.python.org/3.11/whatsnew/3.11.html#new-modules
    # "tomllib",
    # "wsgiref.types",
]
